//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLT.MayLocNuocViet.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreApp.Utilities.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is now active..
        /// </summary>
        public static string ACCOUNT_MSG_ACTIVE_ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_ACTIVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address has been added successfully..
        /// </summary>
        public static string ACCOUNT_MSG_ADD_EMAIL_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_ADD_EMAIL_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change password to activate your account!.
        /// </summary>
        public static string ACCOUNT_MSG_CHANGE_PASSWORD_TO_ACTIVATE {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_CHANGE_PASSWORD_TO_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox to confirm the email address you just added..
        /// </summary>
        public static string ACCOUNT_MSG_CONFIRM_ADD_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_CONFIRM_ADD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to confirm your registration..
        /// </summary>
        public static string ACCOUNT_MSG_CONFIRM_REGISTER_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_CONFIRM_REGISTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is registered but not yet activated..
        /// </summary>
        public static string ACCOUNT_MSG_EMAIL_UNACTIVATED {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_EMAIL_UNACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External user is already registered.
        /// </summary>
        public static string ACCOUNT_MSG_EXTERNAL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_EXTERNAL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider or external access token is not sent.
        /// </summary>
        public static string ACCOUNT_MSG_EXTERNAL_TOKEN_NOT_SENT {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_EXTERNAL_TOKEN_NOT_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External user is not registered.
        /// </summary>
        public static string ACCOUNT_MSG_EXTERNAL_USER_NOT_REGISTER {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_EXTERNAL_USER_NOT_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Provider or External Access Token.
        /// </summary>
        public static string ACCOUNT_MSG_INVALID_PROVIDER {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_INVALID_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same as current password..
        /// </summary>
        public static string ACCOUNT_MSG_NEW_PASSWORD_SAME_CURRENT {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_NEW_PASSWORD_SAME_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change failed..
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_CHANGE_FAILURE {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_CHANGE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logging in with account {0}. Please logout before doing this action..
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_CHANGE_WARNING {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_CHANGE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect. .
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_IS_INCORRECT {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_IS_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed..
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_RESET_FAILURE {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_RESET_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string ACCOUNT_MSG_PASSWORD_RESET_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_PASSWORD_RESET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been re-actived succesfully..
        /// </summary>
        public static string ACCOUNT_MSG_REACTIVE_USER_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_REACTIVE_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already registered..
        /// </summary>
        public static string ACCOUNT_MSG_REGITERED_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_REGITERED_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A register confirmation email has been resent successfully!.
        /// </summary>
        public static string ACCOUNT_MSG_RESEND_REGISTRATION_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_RESEND_REGISTRATION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not allow to reset password..
        /// </summary>
        public static string ACCOUNT_MSG_RESET_PASSWORD_NOT_ALLOW {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_RESET_PASSWORD_NOT_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s password has been reset succesfully. A new password sent to email..
        /// </summary>
        public static string ACCOUNT_MSG_RESET_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_RESET_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to complete password reset..
        /// </summary>
        public static string ACCOUNT_MSG_SENT_RESET_PASSWORD_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_SENT_RESET_PASSWORD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your primary email address..
        /// </summary>
        public static string ACCOUNT_MSG_SET_PRIMARY_EMAIL_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ACCOUNT_MSG_SET_PRIMARY_EMAIL_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LBL_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string LBL_DEPARTMENT {
            get {
                return ResourceManager.GetString("LBL_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template.
        /// </summary>
        public static string LBL_EMAIL_TEMPLATE_SETTING {
            get {
                return ResourceManager.GetString("LBL_EMAIL_TEMPLATE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string LBL_GROUP {
            get {
                return ResourceManager.GetString("LBL_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string LBL_MENU {
            get {
                return ResourceManager.GetString("LBL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string LBL_NOTIFICATION {
            get {
                return ResourceManager.GetString("LBL_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string LBL_PARAMETER {
            get {
                return ResourceManager.GetString("LBL_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string LBL_PRODUCT {
            get {
                return ResourceManager.GetString("LBL_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        public static string LBL_PRODUCT_CATEGORY {
            get {
                return ResourceManager.GetString("LBL_PRODUCT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string LBL_PROJECT {
            get {
                return ResourceManager.GetString("LBL_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string LBL_ROLE {
            get {
                return ResourceManager.GetString("LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LBL_USER {
            get {
                return ResourceManager.GetString("LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LBL_USER_NAME {
            get {
                return ResourceManager.GetString("LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string LBL_VENDOR {
            get {
                return ResourceManager.GetString("LBL_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty policy.
        /// </summary>
        public static string LBL_WARRANTY_POLICY {
            get {
                return ResourceManager.GetString("LBL_WARRANTY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password..
        /// </summary>
        public static string LOGIN_MSG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_MSG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created successfully..
        /// </summary>
        public static string MSG_ADD_SUCCESSED {
            get {
                return ResourceManager.GetString("MSG_ADD_SUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not delete..
        /// </summary>
        public static string MSG_CAN_NOT_DELETE {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not update..
        /// </summary>
        public static string MSG_CAN_NOT_UPDATE {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected record?.
        /// </summary>
        public static string MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This responsible person is neither the responsibility nor authorization of topic. Do you want to add him to the authorization list of topic?.
        /// </summary>
        public static string MSG_CONFIRM_RESPONSIBILITY {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_RESPONSIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new {0} failed..
        /// </summary>
        public static string MSG_CREATE_FAILURE {
            get {
                return ResourceManager.GetString("MSG_CREATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created successfully..
        /// </summary>
        public static string MSG_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string MSG_DATE_INVALID {
            get {
                return ResourceManager.GetString("MSG_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update setting for the current user..
        /// </summary>
        public static string MSG_DID_NOT_UPDATE_SETTINGS {
            get {
                return ResourceManager.GetString("MSG_DID_NOT_UPDATE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail address has already existed..
        /// </summary>
        public static string MSG_EMAIL_IS_EXISTED {
            get {
                return ResourceManager.GetString("MSG_EMAIL_IS_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail address has already existed..
        /// </summary>
        public static string MSG_EMAIL_IS_EXISTED1 {
            get {
                return ResourceManager.GetString("MSG_EMAIL_IS_EXISTED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string MSG_EMAIL_PATTERN_INVALID {
            get {
                return ResourceManager.GetString("MSG_EMAIL_PATTERN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been modified by another user. Refresh page to obtain the latest update..
        /// </summary>
        public static string MSG_ERROR_MODIFY_CONCURRENCY {
            get {
                return ResourceManager.GetString("MSG_ERROR_MODIFY_CONCURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been modified by another user. Refresh page to obtain the latest update..
        /// </summary>
        public static string MSG_ERROR_MODIFY_CONCURRENCY1 {
            get {
                return ResourceManager.GetString("MSG_ERROR_MODIFY_CONCURRENCY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered an unknown error..
        /// </summary>
        public static string MSG_ERROR_UNEXPECTED {
            get {
                return ResourceManager.GetString("MSG_ERROR_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string MSG_FIELD_REQURIED {
            get {
                return ResourceManager.GetString("MSG_FIELD_REQURIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string MSG_GREATER_THAN {
            get {
                return ResourceManager.GetString("MSG_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string MSG_INVALID_REQUEST {
            get {
                return ResourceManager.GetString("MSG_INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your link has expired..
        /// </summary>
        public static string MSG_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("MSG_INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string MSG_IS_EXISTED {
            get {
                return ResourceManager.GetString("MSG_IS_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group has already existed.
        /// </summary>
        public static string MSG_IS_EXISTED_GROUP {
            get {
                return ResourceManager.GetString("MSG_IS_EXISTED_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked..
        /// </summary>
        public static string MSG_IS_LOCKED {
            get {
                return ResourceManager.GetString("MSG_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string MSG_IS_NOT_EXISTED {
            get {
                return ResourceManager.GetString("MSG_IS_NOT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found..
        /// </summary>
        public static string MSG_IS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_IS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not matched..
        /// </summary>
        public static string MSG_IS_NOT_MATCHED {
            get {
                return ResourceManager.GetString("MSG_IS_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string MSG_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("MSG_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string MSG_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string MSG_IS_REQUIRED1 {
            get {
                return ResourceManager.GetString("MSG_IS_REQUIRED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string MSG_ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked due to multiple failed login attempt..
        /// </summary>
        public static string MSG_LOCKED_ACCOUNT {
            get {
                return ResourceManager.GetString("MSG_LOCKED_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string MSG_NO_DATA {
            get {
                return ResourceManager.GetString("MSG_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        public static string MSG_NO_RESULT {
            get {
                return ResourceManager.GetString("MSG_NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not activated..
        /// </summary>
        public static string MSG_NOT_ACTIVATED {
            get {
                return ResourceManager.GetString("MSG_NOT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist in the system..
        /// </summary>
        public static string MSG_NOT_EXISTED {
            get {
                return ResourceManager.GetString("MSG_NOT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be between 8 and 20 characters..
        /// </summary>
        public static string MSG_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match..
        /// </summary>
        public static string MSG_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one UPPERCASE, one lowercase, and one number..
        /// </summary>
        public static string MSG_PASSWORD_PATTERN_INVALID {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_PATTERN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string MSG_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("MSG_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select record(s) first..
        /// </summary>
        public static string MSG_SELECT_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SELECT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email failed..
        /// </summary>
        public static string MSG_SEND_EMAIL_FAILURE {
            get {
                return ResourceManager.GetString("MSG_SEND_EMAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time.
        /// </summary>
        public static string MSG_TIME_INVALID {
            get {
                return ResourceManager.GetString("MSG_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        public static string MSG_UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been unlocked succesfully..
        /// </summary>
        public static string MSG_UNLOCK_USER_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UNLOCK_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} failed..
        /// </summary>
        public static string MSG_UPDATE_FAILURE {
            get {
                return ResourceManager.GetString("MSG_UPDATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been activated again successfully..
        /// </summary>
        public static string MSG_UPDATE_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPDATE_STATUS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string MSG_UPDATE_SUCCESSED {
            get {
                return ResourceManager.GetString("MSG_UPDATE_SUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System only support file types as: {0}.
        /// </summary>
        public static string MSG_UPLOAD_FILE_TYPES_SUPPORTED {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_FILE_TYPES_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System only support uploading {0} files.
        /// </summary>
        public static string MSG_UPLOAD_MAX_FILES_LIMIT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_MAX_FILES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is larger than {1}MB..
        /// </summary>
        public static string MSG_UPLOAD_MAX_SIZE_LIMIT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_MAX_SIZE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System only support minimum dimension of image {0}px x {1}px.
        /// </summary>
        public static string MSG_UPLOAD_MIN_DIMENSION {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_MIN_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Username has already existed..
        /// </summary>
        public static string MSG_USER_NAME_IS_EXISTED {
            get {
                return ResourceManager.GetString("MSG_USER_NAME_IS_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. You have {0} more attempt(s) before your account gets locked out..
        /// </summary>
        public static string MSG_WARNING_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("MSG_WARNING_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdate is not bigger enddate..
        /// </summary>
        public static string PROJECT_MSG_VALIDATE_STARTDATE_ENDDATE {
            get {
                return ResourceManager.GetString("PROJECT_MSG_VALIDATE_STARTDATE_ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ROLE_LBL_ROLE {
            get {
                return ResourceManager.GetString("ROLE_LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string USER_LBL_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("USER_LBL_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string USER_LBL_DELETE_TITLE {
            get {
                return ResourceManager.GetString("USER_LBL_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set multiple roles for guest..
        /// </summary>
        public static string USER_MANAGEMENT_GUESS_ROLE_INVALID {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_GUESS_ROLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ACTIONS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User as Guest.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ADD_NEW_GUEST {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ADD_NEW_GUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ADD_NEW_USER {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ADD_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_COMPANY {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to find the company.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_COMPANY_PLACE_HOLDER {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_COMPANY_PLACE_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_DEPARTMENT {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to find the department.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_DEPARTMENT_PLACE_HOLDER {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_DEPARTMENT_PLACE_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator note.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_EMAIL {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FILTER_COMPANY {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FILTER_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FILTER_DEPARTMENT {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FILTER_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FILTER_KEYWORD {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FILTER_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FILTER_ROLE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FILTER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FILTER_STATUS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FILTER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_FIRST_NAME {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_LAST_NAME {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ROLE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ROLE_NAME {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s).
        /// </summary>
        public static string USER_MANAGEMENT_LBL_ROLES {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter keyword....
        /// </summary>
        public static string USER_MANAGEMENT_LBL_SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_SELECT_ROLE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_SELECT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_SELECT_ROLE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_SELECT_ROLE_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_STATUS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string USER_MANAGEMENT_LBL_TITLE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_LBL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new user failed..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_CREATE_FAILURE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_CREATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created successfully..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deactivated successfully..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_DEACTIVE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_DEACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be deleted because it is associated with other data..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_DELETE_FAIL {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting an user failed..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_DELETE_FAILURE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_DELETE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted successfully..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A guest cannot have other roles.
        /// </summary>
        public static string USER_MANAGEMENT_MSG_GUEST_ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_GUEST_ROLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not existed..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_NOT_EXISTED {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_NOT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to re-activate this user?.
        /// </summary>
        public static string USER_MANAGEMENT_MSG_REACTIVATE_USER_CONFIRM {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_REACTIVATE_USER_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign roles to user..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_ROLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlock this user?.
        /// </summary>
        public static string USER_MANAGEMENT_MSG_UNLOCK_USER_CONFIRM {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_UNLOCK_USER_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating an user failed..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_UPDATE_FAILURE {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_UPDATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated successfully..
        /// </summary>
        public static string USER_MANAGEMENT_MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT_MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Confirmation failed..
        /// </summary>
        public static string USER_REGISTER_CONFIRMATION_FAIL {
            get {
                return ResourceManager.GetString("USER_REGISTER_CONFIRMATION_FAIL", resourceCulture);
            }
        }
    }
}
